# Generated by Django 2.2.7 on 2019-11-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskid', models.AutoField(primary_key=True, serialize=False)),
                ('taskdesc', models.CharField(max_length=1000)),
                ('assigned_to', models.CharField(choices=[('avnish', 'AVNISH'), ('akhilesh', 'AKHILESH'), ('smijith', 'SMIJITH'), ('vinod', 'VINOD'), ('ankur', 'ANKUR')], max_length=16)),
                ('deadline', models.DateField(max_length=20)),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
